---
title: "Chatbots Visualization"
output: html_notebook
---

Loading data and getting and tidying up.

```{r}
files <- list.files(path=".", pattern="*.txt", full.names=T, recursive=FALSE)
list <- c()
list <- lapply(files, name <- function(x) {
   i <- list
  log <- tibble(x = read_lines(x)) %>% filter_all(any_vars(str_detect(., "INFO:tensorflow:Saving evaluation summary")))
  list <- c(i, log)
})
validation = bind_cols(list) %>%
  rename("0.1" = x, "0.2" = x1, "0.3" = x2, "0.4" = x3, "0.5" = x4, "0.6" = x5, "0.7" = x6, "0.8" = x7, "0.9" = x8, "1" = x9, "0.0" = x10) %>%
  gather(case, value) %>%
  separate(value, into = c("info", "tf", "step", "losses"), sep = ":") %>%
  select(-info, -tf) %>%
  separate(losses, into = c("loss", "recall_at_1", "recall_at_10", "recall_at_2", "recall_at_5"), sep = ",") %>%
  separate_rows( -step, -case, sep = " = ") %>%
  filter(loss != " loss") %>%
  mutate_at(c("case" ,"step", "loss", "recall_at_1", "recall_at_10", "recall_at_2", "recall_at_5"),parse_number)
validation
```

```{r}
ggplot(data = validation) + 
  geom_line(mapping = aes(x = step, y = recall_at_1, colour = factor(case)), size = 1) +
  scale_color_manual(values = colorRampPalette(c( "#08519C","#EFF3FF"))(11)) +
  theme(panel.background = element_rect(fill = "tan1")) +
  labs(x = "Training Epochs", y = "Accuracy", color = "")
```



```{r}
max_acc <- validation %>%
  group_by(case) %>%
  summarise(max_acc = max(recall_at_1))

ggplot(data = max_acc, aes(x = case, y = max_acc, fill = case)) +
  geom_col() +
  scale_fill_distiller(palette = "Blues")  +
  labs(x = "Noise probability P", y = "Testing Accuracy", fill = "") +
  theme(panel.background = element_rect(fill = "tan1"))
```


```{r}
colourCount <- length(unique(mtcars$hp)) # number of levels
getPalette <- colorRampPalette(brewer.pal(9, "Set1"))
brewer.pal(11, "Blues")
## Now you can draw your 15 different factors
g <- ggplot(validation) 
g <- g +  geom_line(aes(x = step, y = recall_at_1, colour = factor(case))) 
g <- g +  scale_color_manual(values = colorRampPalette(c("#F7FBFF", "#08306B"), alpha = TRUE)(11)) 
g <- g + theme(legend.position="top")
g <- g + xlab("X axis name") + ylab("Frequency (%)")
g
brewer.pal(name ="Blues", n=5)
distiller.pal()
```

